[build]
  builder = "nixpacks"
  buildCommand = "npm install && npm run build"
  startCommand = "npm start"
  watchPatterns = ["**"]
  nixpacksSourcePath = "."

[build.environment]
  NPM_CONFIG_PRODUCTION = "false"
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=4096"

[deploy]
  startCommand = "node dist/server.js"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 100
  restartDelay = "5s"
  restartMaxRetries = 5
