[build]
  builder = "nixpacks"
  buildCommand = "npm install && npm run build"
  
[build.environment]
  NPM_CONFIG_PRODUCTION = "false"
  NODE_ENV = "production"
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=4096"
  PRISMA_CLI_BINARY_TARGETS = "linux-musl-openssl-3.0.x"
  CI = "true"

[deploy]
  startCommand = "node dist/server.js"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 30
